### ISSUE TITLE
1.7.0 Release TODO

### ISSUE THREAD

**Issue by tchx84** [tchx84/Flatseal#264]
- [x] Fix offline documentation styling for mobile, e.g. use media queries to remove side spacing. See #268
- [x] Add a quick introduction for both static and dynamic permissions to the docs. See #267
- [x] Update translations. See #265
- [x] Update screenshot. See #269

Pending:
1. https://gitlab.gnome.org/somas/apostrophe/-/merge_requests/229
